dataset:
  name: iac_mortality
  raw_file: data/raw/full_cohort_data.csv

target:
  column: day_28_flg

paths:
  raw_dir: data/raw
  processed_dir: data/processed
  processed_file: data/processed/diabetes.parquet